GET http://localhost:3030/users
########
POST http://localhost:3030/users HTTP/1.1
content-type: application/json

{
    "userName":"valennna",
    "email":"io@email.it",
    "password":"ciaociao",
    "firstName": "gnagna",
    "lastName": "djlijld"
}
######
DELETE http://localhost:3030/users/6362c079c4e769d526d8b4aa HTTP/1.1
######
PATCH http://localhost:3030/users/6362c487fbecba4b1e8c7c56 HTTP/1.1
content-type: application/json

{
    "userName":"valeXXX"
}

#####

POST http://localhost:3030/login/userName
content-type: application/json

{
    "userName": "valettbbntina"
}
#####
POST http://localhost:3030/login/password
content-type: application/json

{
    "password": "pabsspss11"
}

#####
POST http://localhost:3030/login HTTP/1.1
content-type: application/json

{
    "email":"io@email.it",
    "password":"ciaociao"
}
######